spring:
  datasource:
    url: jdbc:postgresql://192.168.1.143:5432/liceum
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

service:
  pathToFile: "C:/user.ivan/lyceum_homework/Project/Files/"

data:
  folder: /home/liceum/documents